### ISSUE TITLE
Market #32 still active after deadline

### ISSUE THREAD

**Issue by contractormario** [EveripediaNetwork/prediqt-public-issues#2]
**Describe the bug**
It's 15 Feb, 13:45 UTC and https://prediqt.everipedia.org/market/32 is still active.

**Expected behavior**
Market should be resolved and closed.

**Comment by kesar** [comment]
+1

Its resolved onchain, it needs a fix on the API side

**Comment by kesar** [comment]
market 32 deadline was set by creator for Feb 15 2020 23:59, so it was ok not being resolved. It got resolved today 16th by the oracle 👍 
--
